In [0]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

np.random.seed(42)
%matplotlib inline

In [0]:
# solo = np.loadtxt("amostras_solo.tsv", delimiter="\t", dtype=str)
# solo_new = [a.replace(",", ".") for i in solo for a in i]
# solo_new = np.array(solo_new, dtype=float)
# np.savetxt('amostras_solo.csv', solo_new.reshape(-1, 4), delimiter=';')

### Covariance Matrix

### Testing with Pandas

In [7]:
solo = pd.read_csv("amostras_solo.csv", sep=';', index_col=False, header=None)
solo.describe()

0         1          2          3
count  24.000000  24.00000  24.000000  24.000000
mean   67.779167  22.11250  10.195833   2.833333
std     8.259697   6.31646   3.097752   0.828129
min    55.900000  10.50000   5.800000   0.900000
25%    61.200000  16.67500   7.500000   2.500000
50%    67.450000  22.95000  10.150000   2.850000
75%    73.350000  27.95000  12.400000   3.425000
max    83.700000  32.80000  17.600000   4.400000

In [8]:
## Remove mean
solo = solo.sub(solo.mean(axis=0), axis=1)

solo.describe()

0             1             2             3
count  2.400000e+01  2.400000e+01  2.400000e+01  2.400000e+01
mean  -1.776357e-15  2.516506e-15  4.070818e-16 -1.665335e-16
std    8.259697e+00  6.316460e+00  3.097752e+00  8.281287e-01
min   -1.187917e+01 -1.161250e+01 -4.395833e+00 -1.933333e+00
25%   -6.579167e+00 -5.437500e+00 -2.695833e+00 -3.333333e-01
50%   -3.291667e-01  8.375000e-01 -4.583333e-02  1.666667e-02
75%    5.570833e+00  5.837500e+00  2.204167e+00  5.916667e-01
max    1.592083e+01  1.068750e+01  7.404167e+00  1.566667e+00

In [9]:
# Covariance Matrix
R = np.cov(solo.values, rowvar=False)
R

array([[ 6.82225906e+01, -4.89179891e+01, -1.83770471e+01,
         1.79855072e+00],
       [-4.89179891e+01,  3.98976630e+01,  8.52005435e+00,
        -1.81391304e+00],
       [-1.83770471e+01,  8.52005435e+00,  9.59606884e+00,
        -1.33333333e-02],
       [ 1.79855072e+00, -1.81391304e+00, -1.33333333e-02,
         6.85797101e-01]])

### Eigenvalues and Eigenvectors

In [10]:
w, v = np.linalg.eig(R)

print(f"Autovalores: \n {w}")
print(f"autovetores: \n {v}")

Autovalores: 
 [1.09000351e+02 8.76841593e+00 5.00793609e-02 5.83272977e-01]
autovetores: 
 [[-0.7883585   0.22932877 -0.57020122 -0.02774445]
 [ 0.58281083  0.57076064 -0.57766829  0.0293799 ]
 [ 0.19570169 -0.78479305 -0.58217957 -0.08287138]
 [-0.02287486 -0.07576589 -0.04729555  0.99574063]]


### Ordenando

In [0]:
#from max to min

indexes = np.argsort(w)[::-1]
w_ordered = w[indexes]
#indexes = [np.where(w == a)[0][0] for a in w_ordered]

In [12]:
v_ordered = v[:,indexes]
print(f"Autovalores ordenados: \n{w_ordered}")
print(f"Autovetores ordenados: \n{v_ordered}")



Autovalores ordenados: 
[1.09000351e+02 8.76841593e+00 5.83272977e-01 5.00793609e-02]
Autovetores ordenados: 
[[-0.7883585   0.22932877 -0.02774445 -0.57020122]
 [ 0.58281083  0.57076064  0.0293799  -0.57766829]
 [ 0.19570169 -0.78479305 -0.08287138 -0.58217957]
 [-0.02287486 -0.07576589  0.99574063 -0.04729555]]


In [13]:
w_ordered / np.sum(w_ordered)


array([9.20594595e-01, 7.40562412e-02, 4.92620385e-03, 4.22960003e-04])

### Cálculo das componentes

In [0]:
# Components 


a = np.matmul(v_ordered, solo.values.T)

In [15]:
print(a)

[[-1.15941563e+01 -9.51164881e+00 -1.16192502e+00  3.77337440e+00
   4.32214592e-01 -1.15909482e+00  6.00829192e+00 -4.08963192e+00
  -1.59857600e+01  2.46420852e+00  7.17917108e+00  1.08774356e+00
  -5.24127085e+00  7.73997128e+00  6.86658500e+00 -7.00759483e+00
  -1.28497718e+01 -3.47119774e+00  1.02693501e+01  1.16333052e+01
   6.39370280e+00  8.16321698e+00 -8.46725791e+00  8.52817454e+00]
 [ 1.98980536e+00  3.03521028e+00  4.38777171e-01 -4.10638914e+00
   2.76002964e+00 -1.80139657e+00 -1.71338652e+00  9.23461449e-02
   1.61671323e+00  2.82485663e+00 -1.67035946e+00  7.50145517e-03
  -8.05990133e-01  6.35131866e-01  4.96593260e-01  9.63531646e-01
   9.50268287e-01  1.25018639e-01 -2.49558987e+00 -9.44907116e-01
  -1.59116118e-01 -1.32735984e+00  1.85989368e+00 -2.77118251e+00]
 [ 8.87663695e+00  7.10202353e+00 -4.69039248e-01 -1.85123193e-01
   4.14303677e-01  1.07347512e+00 -3.38556305e+00  2.66964172e+00
   1.16813508e+01 -2.42717023e+00 -6.66602111e+00 -1.17400662e+00
   7.292

In [32]:
b=np.var(a,axis=1)
print(b)
porcentagem=b/np.sum(b)
print(porcentagem)

[60.94646888  3.35878581 40.38995097  8.77349225]
[0.53712143 0.02960099 0.35595677 0.07732082]


#### variancia percentual

In [0]:
#Variancia dos componentes
# var_components = np.array([data.var() for data in a])
# var_components

In [17]:
#porcentagem das variancias dos componentes
var_comp_per = w_ordered / np.sum(w_ordered)
#var_comp_per = var_components / np.sum(var_components)
var_comp_per

array([9.20594595e-01, 7.40562412e-02, 4.92620385e-03, 4.22960003e-04])

### A ordenação a partir da celula anterior ficaria X1, X2, x3, x4



### Voltando ao espaco dos dados atraves das componentes e comparando com o que tinha antes (eh para dar igual)

In [18]:
x = np.matmul(a.T, v_ordered)
x[:,0]

array([ 12.12083333,  10.72083333,   1.12083333,  -5.57916667,
         1.42083333,   0.02083333,  -6.47916667,   3.82083333,
        15.92083333,  -0.67916667,  -7.97916667,  -1.07916667,
         5.02083333,  -6.87916667,  -6.37916667,   7.22083333,
        12.72083333,   3.52083333, -11.17916667, -11.87916667,
        -6.27916667,  -8.57916667,   9.12083333,  -9.77916667])

In [19]:
solo.values[:,0]

array([ 12.12083333,  10.72083333,   1.12083333,  -5.57916667,
         1.42083333,   0.02083333,  -6.47916667,   3.82083333,
        15.92083333,  -0.67916667,  -7.97916667,  -1.07916667,
         5.02083333,  -6.87916667,  -6.37916667,   7.22083333,
        12.72083333,   3.52083333, -11.17916667, -11.87916667,
        -6.27916667,  -8.57916667,   9.12083333,  -9.77916667])

### Using GHA

In [0]:
class GHA():
  
  def __init__(self, n=1, j=4, i=4, learning=0.0001):
    
    self.n = n
    self.n_outputs = j
    self.n_inputs = i
    self.learning_rate = learning
    self.w = np.random.randn(j, i)
    self.y = np.zeros(j)
   
  def fit(self, x):
    
    for it in range(self.n):
      #for out in range(self.n_outputs):
        #Sprint(np.dot(self.w[out,:], x))
      self.y = np.dot(self.w, x)
      dW = (np.outer(self.y,x) - np.dot(np.tril(np.outer(self.y,self.y)),self.w))*self.learning_rate
      self.w += dW
  def brief(self):
    
    return self.y, self.w

In [21]:
gha = GHA(j=4)

for _ in range(10000):
  for x in solo.values:
    gha.fit(x)

y, wgha = gha.brief()
print(y)
print(wgha)

## um dos autovetores pelo GHA eh diferente

[-11.70769522   2.41242254   0.66940103  -0.1024271 ]
[[ 0.78781864 -0.58416684 -0.19454459  0.02156135]
 [-0.22671555 -0.573468    0.78499752  0.07444207]
 [-0.0313253   0.01819078 -0.07180832  0.99734984]
 [-0.01108425 -0.01884771  0.00371979 -0.21712533]]


In [22]:
print(w)
print(v.T)

[1.09000351e+02 8.76841593e+00 5.00793609e-02 5.83272977e-01]
[[-0.7883585   0.58281083  0.19570169 -0.02287486]
 [ 0.22932877  0.57076064 -0.78479305 -0.07576589]
 [-0.57020122 -0.57766829 -0.58217957 -0.04729555]
 [-0.02774445  0.0293799  -0.08287138  0.99574063]]


## USando o SKlearn para achar as compoenentes e comparar com as achadas anteriormente pelos outros metodos

In [23]:

from sklearn.decomposition import PCA

pca =PCA(n_components=4)
pca.fit(solo.values)


PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [24]:
pca.components_

array([[ 0.7883585 , -0.58281083, -0.19570169,  0.02287486],
       [-0.22932877, -0.57076064,  0.78479305,  0.07576589],
       [ 0.02774445, -0.0293799 ,  0.08287138, -0.99574063],
       [ 0.57020122,  0.57766829,  0.58217957,  0.04729555]])

Deu igual. Com excessao do GHA que encontrou uma das componentes diferente

In [25]:
pca.explained_variance_ratio_

array([9.20594595e-01, 7.40562412e-02, 4.92620385e-03, 4.22960003e-04])